name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MACOSX_DEPLOYMENT_TARGET: 12.0

jobs:
  Build:
    name: mathfn CI (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment.yml

      - uses: hendrikmuhs/ccache-action@main
        with:
          variant: sccache
          key: ${{ github.job }}-${{ matrix.os }}

      - name: Setup Platform
        shell: bash -l {0}
        run: |
            echo "LFORTRAN_CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
            echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
            echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV

      - name: Build (Linux / macOS)
        shell: bash -l {0}
        run: |
            git clone https://github.com/lcompilers/lpython.git
            cd lpython
            git checkout v0.6.0
            xonsh ci/build.xsh
            cd ..

      - name: Test (Linux / macOS)
        shell: bash -l {0}
        run: |
            PYTHONPATH="src:$(lpython --get-rtlib-header-dir)/../ltypes" python examples/example_sin.py
            (cd src && lpython ../examples/example_sin.py)
